services:
  local-sql:
    container_name: local-sql
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    volumes:
      - lsql:/app/db
    # environment:
    #   REQUIRE_TOKEN: "true"
    ports:
      - 57597:57597
volumes:
  lsql:
