import {
  Bug,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  Computer,
  Database,
  Ellipsis,
  Eye,
  KeyRound,
  LifeBuoy,
  Loader2,
  MoonStar,
  Plus,
  Power,
  Send,
  Server,
  Settings,
  Settings2,
  SquareTerminal,
  Sun,
  SunMoon,
  TableProperties,
  Trash2,
  TriangleAlert,
  Unplug,
  Wrench,
} from "lucide-react";
import { FiGithub } from "react-icons/fi";

export const Icons = {
  Github: FiGithub,
  Loader: Loader2,
  Sun,
  MoonStar,
  SunMoon,
  Computer,
  LifeBuoy,
  Send,
  Connect: Power,
  Disconnect: Unplug,
  Wrench,
  SquareTerminal,
  Plus,
  ChevronLeft,
  ChevronsLeft,
  ChevronRight,
  ChevronsRight,
  Table: TableProperties,
  Database,
  Server,
  Ellipsis,
  Settings,
  Trash: Trash2,
  TriangleAlert,
  Eye,
  Key: KeyRound,
  Sliders: Settings2,
  Bug,
};

export type IconName = keyof typeof Icons;
export type IconType = (typeof Icons)[IconName];
