name: Test remote cache

on: push

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }} 
    strategy:
      fail-fast: true
      matrix:
        package: ["api"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun.js
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun i

      - name: Build ${{ matrix.package }}
        run: VERCEL_TARGET_ENV=preview bun run build:${{ matrix.package }}